services:
 frontend:
  build:
  context: ./app/frontend/
  dockerfile: frontend.Dockerfile
  ports:
  - "3000:3000"
  depends_on:
  - server
 server:
  build:
  context: ./app/server/
  dockerfile: py.Dockerfile
  ports:
  - "443:443"
  
  
